In [13]:
from multiprocessing import Process
from omegastream.minibatch import stream

db = om.datasets.mongodb

# fixed size -- emits windows of fixed sizes
@stream('test', size=2, keep=True)
def myprocess(window):
    try:
        db.processed.insert_one({'data': window.data or {}})
        print(window.data)
    except Exception as e:
        print(e)
    return window

[{'date': '2018-04-30T20:18:22.918060'}, {'date': '2018-04-30T20:18:23.481320'}]
[{'date': '2018-04-30T20:18:24.041337'}, {'date': '2018-04-30T20:18:24.593545'}]

KeyboardInterrupt:

In [14]:
# relaxed time windows -- emits all documents within most recent interval
from multiprocessing import Process
from omegastream.minibatch import stream

db = om.datasets.mongodb

@stream('test', interval=1, keep=True)
def myprocess(window):
    print("ok")
    try:
        print(window.data)
        db.processed.insert_one({'data': window.data or {}})
    except Exception as e:
        print(e)
    return window

KeyboardInterrupt:

In [15]:
# fixed time windows -- emits documents that were inserted in exactly a given time interval
from multiprocessing import Process
from omegastream.minibatch import stream
import datetime 

db = om.datasets.mongodb

@stream('test', interval=2, relaxed=False, keep=True)
def myprocess(window):
    print(datetime.datetime.now())
    try:
        print(window.data)
        db.processed.insert_one({'data': window.data or {}})
    except Exception as e:
        print(e)
    return window

2018-04-30 20:18:41.772507
[]
2018-04-30 20:18:41.922504
[]
2018-04-30 20:18:42.076129
[]
2018-04-30 20:18:42.222734
[]
2018-04-30 20:18:42.376430
[]
2018-04-30 20:18:42.516643
[]
2018-04-30 20:18:42.657077
[]
2018-04-30 20:18:45.076585
[]
2018-04-30 20:18:47.476397
[]
2018-04-30 20:18:47.621012
[]
2018-04-30 20:18:50.022696
[]
2018-04-30 20:18:52.420408
[]
2018-04-30 20:18:54.851020
[]
2018-04-30 20:18:57.270432
[]
2018-04-30 20:18:59.680508
[]
2018-04-30 20:18:59.833289
[]
2018-04-30 20:19:02.246753
[]
2018-04-30 20:19:04.662475
[]
2018-04-30 20:19:07.076975
[]
2018-04-30 20:19:09.478584
[]
2018-04-30 20:19:09.632436
[]
2018-04-30 20:19:12.032225
[]
2018-04-30 20:19:14.449306
[]
2018-04-30 20:19:16.874338
[]

KeyboardInterrupt:

In [30]:
from omegaml.mdataframe import MDataFrame

coll = om.datasets.mongodb['window']
mdf = MDataFrame(coll)
mdf.query(created__ne=None).value

,created,data,processed,stream
0,2018-04-30 19:39:06.612,"[{'date': '2018-04-30T19:39:00.848991'}, {'dat...",True,test
1,2018-04-30 19:39:06.956,"[{'date': '2018-04-30T19:39:01.527029'}, {'dat...",True,test
2,2018-04-30 19:39:07.224,"[{'date': '2018-04-30T19:39:02.639710'}, {'dat...",True,test
3,2018-04-30 19:39:07.484,"[{'date': '2018-04-30T19:39:03.749000'}, {'dat...",True,test
4,2018-04-30 19:39:07.746,"[{'date': '2018-04-30T19:39:04.850384'}, {'dat...",True,test
5,2018-04-30 19:39:08.008,"[{'date': '2018-04-30T19:39:05.953539'}, {'dat...",True,test
6,2018-04-30 19:39:08.261,"[{'date': '2018-04-30T19:39:07.062142'}, {'dat...",True,test
7,2018-04-30 19:39:08.875,"[{'date': '2018-04-30T19:39:08.173570'}, {'dat...",True,test
8,2018-04-30 19:39:09.958,"[{'date': '2018-04-30T19:39:09.284564'}, {'dat...",True,test
9,2018-04-30 19:39:11.040,"[{'date': '2018-04-30T19:39:10.380515'}, {'dat...",True,test
10,2018-04-30 19:39:12.138,"[{'date': '2018-04-30T19:39:11.487881'}, {'dat...",True,test
11,2018-04-30 19:39:13.339,"[{'date': '2018-04-30T19:39:12.593584'}, {'dat...",True,test
12,2018-04-30 19:39:14.399,"[{'date': '2018-04-30T19:39:13.698274'}, {'dat...",True,test
13,2018-04-30 19:39:15.497,"[{'date': '2018-04-30T19:39:14.797019'}, {'dat...",True,test
14,2018-04-30 19:39:16.585,"[{'date': '2018-04-30T19:39:15.896915'}, {'dat...",True,test
15,2018-04-30 19:39:17.680,"[{'date': '2018-04-30T19:39:17.008639'}, {'dat...",True,test
16,2018-04-30 19:39:18.899,"[{'date': '2018-04-30T19:39:18.112365'}, {'dat...",True,test
17,2018-04-30 19:39:19.981,"[{'date': '2018-04-30T19:39:19.248710'}, {'dat...",True,test
18,2018-04-30 19:39:23.725,"[{'date': '2018-04-30T19:39:20.358308'}, {'dat...",True,test
19,2018-04-30 19:39:24.420,"[{'date': '2018-04-30T19:39:23.682642'}, {'dat...",True,test
20,2018-04-30 19:39:25.100,[{'date': '2018-04-30T19:39:24.794628'}],True,test
21,2018-04-30 19:39:25.764,[{'date': '2018-04-30T19:39:25.345749'}],True,test
22,2018-04-30 19:39:26.437,[{'date': '2018-04-30T19:39:25.903391'}],True,test
23,2018-04-30 19:39:27.136,"[{'date': '2018-04-30T19:39:26.455884'}, {'dat...",True,test
24,2018-04-30 19:39:27.813,[{'date': '2018-04-30T19:39:27.572350'}],True,test
25,2018-04-30 19:39:28.484,[{'date': '2018-04-30T19:39:28.127414'}],True,test
26,2018-04-30 19:39:29.150,[{'date': '2018-04-30T19:39:28.680807'}],True,test
27,2018-04-30 19:39:29.820,[{'date': '2018-04-30T19:39:29.230586'}],True,test
28,2018-04-30 19:39:30.499,"[{'date': '2018-04-30T19:39:29.787175'}, {'dat...",True,test
29,2018-04-30 19:39:31.178,[{'date': '2018-04-30T19:39:30.898405'}],True,test
...,...,...,...,...
1241,2018-04-30 20:18:11.482,[],True,test
1242,2018-04-30 20:18:13.912,[],True,test
1243,2018-04-30 20:18:16.327,[],True,test
1244,2018-04-30 20:18:18.746,[],True,test
1245,2018-04-30 20:18:27.088,"[{'date': '2018-04-30T20:18:22.918060'}, {'dat...",True,test
1246,2018-04-30 20:18:27.370,"[{'date': '2018-04-30T20:18:24.041337'}, {'dat...",True,test
1247,2018-04-30 20:18:41.720,[],True,test
1248,2018-04-30 20:18:41.869,[],True,test
1249,2018-04-30 20:18:42.028,[],True,test
1250,2018-04-30 20:18:42.166,[],True,test
1251,2018-04-30 20:18:42.328,[],True,test
1252,2018-04-30 20:18:42.468,[],True,test
1253,2018-04-30 20:18:42.613,[],True,test
1254,2018-04-30 20:18:45.022,[],True,test
1255,2018-04-30 20:18:47.426,[],True,test
1256,2018-04-30 20:18:47.570,[],True,test
1257,2018-04-30 20:18:49.975,[],True,test
1258,2018-04-30 20:18:52.374,[],True,test
1259,2018-04-30 20:18:54.794,[],True,test
1260,2018-04-30 20:18:57.205,[],True,test
1261,2018-04-30 20:18:59.624,[],True,test
1262,2018-04-30 20:18:59.784,[],True,test
1263,2018-04-30 20:19:02.192,[],True,test
1264,2018-04-30 20:19:04.616,[],True,test
1265,2018-04-30 20:19:07.026,[],True,test
1266,2018-04-30 20:19:09.422,[],True,test
1267,2018-04-30 20:19:09.581,[],True,test
1268,2018-04-30 20:19:11.974,[],True,test
1269,2018-04-30 20:19:14.384,[],True,test
1270,2018-04-30 20:19:16.811,[],True,test